language: python

python:
 - "2.7"

install:
 - sudo apt-get update
 - sudo apt-get install python2.7-dev python-m2crypto python-psycopg2
 - sudo apt-get install openjdk-6-jdk dejagnu checkstyle gcj-jdk jclassinfo
 - pip install -r requirements.txt

script:
 - ./src/manage-test.py test accounts attestation checker configuration sessionprofile solutions tasks
