language: python

python:
 - "2.7"

install:
 - sudo apt-get update
 - sudo apt-get install python2.7-dev swig libsasl2-dev libssl-dev libpq-dev
 - sudo apt-get install openjdk-6-jdk dejagnu checkstyle gcj-jdk jclassinfo
   # m2crypto does not compile out of the box, see https://github.com/boto/boto/pull/841
 - pip install --upgrade git+https://github.com/martinpaljak/M2Crypto
 - pip install -r requirements.txt

script:
 - ./src/manage-test.py test accounts attestation checker configuration sessionprofile solutions tasks
